### ISSUE TITLE
template is not cached, it is downloaded each time.

### ISSUE THREAD

**Issue by DongShi** [wikieswan/vipspa#2]
页面html 没有缓存，每次访问都需要再fetch一遍。

**Comment by wikieswan** [comment]
已增加缓存html的feature。考虑到js静态资源，一次加载后，之后就304请求，暂时不考虑手动维护js缓存，默认使用浏览器对js的缓存

**Comment by dayney** [comment]
html是有缓存，但是js文件没有缓存，每次都是重新加载的，参考layui可以做到缓存，主要是做一个js文件的加载状态的`status`的管理，如过是`false`就需要重新加载，加载完成后改为`true`,下载加载时候，在判断下该js的是否被缓存的

**Comment by wikieswan** [comment]
@krui0728 你可以提repo上来
