### ISSUE TITLE
不同路由所引用内容怎样结束其生命周期。

### ISSUE THREAD

**Issue by yang123guo** [wikieswan/vipspa#4]
您好，很高兴使用您的vipspa，使用过程中发现当a.html页面引用了a.js，当跳转到b.html的时候引用b.js，此时a.js的代码还在起作用，这个会导致一些问题。比如（  $(window).on('scroll' , function(){ }) ）等事件。怎么使得此时a.js不再作用？？

**Comment by wikieswan** [comment]
因为是单页面，spa，所以你的全局事件或者函数会一直起作用。
如果不想让全局事件起作用，可以在其他页面做remove操作
比如  $(window).off('scroll')
