### ISSUE TITLE
controller中可以传多个值吗，比如多个js或css

### ISSUE THREAD

**Issue by 992forever** [wikieswan/vipspa#5]
controller中可以传多个值吗？比如多个js或css。如果可以，具体的写法是怎样的呢？

**Comment by wikieswan** [comment]
你好，首先感谢使用。
controller只可以传递一个值，一个view对应一个controller。
如果你想在controller中加载其他js或则css，可以通过一些辅助的js代码来实现。
比如参考源代码的 loadScript ，目前没有把它暴露出来，它是私有方法。
