### ISSUE TITLE
关于嵌套路由

### ISSUE THREAD

**Issue by cfk199244** [wikieswan/vipspa#6]
你好，我想问一下对于嵌套路由是否应该怎么做？？

比如我a界面上有3个文本框, 填入了前2个. 点击第3个文本框跳转到了b页面去处理选择. 选择后返回a页面，或者点击b页面的返回.
这是a页面已输入的内容就被覆盖了.

**Comment by wikieswan** [comment]
这个项目当初是以简单和小巧而立项的，没有设计嵌套路由。现在用的人多了，越来越多人提出这个需求，那么近期下个版本就把这个feature加进去。

回到你的问题，临时解决方案是在A页面以弹窗的形式进去B。

新版本会尽快发出来的。

**Comment by cfk199244** [comment]
@wikieswan 好的，非常感谢.

**Comment by wikieswan** [comment]
已增加嵌套路由支持，分支 https://github.com/wikieswan/vipspa/tree/v2 
你可以先用起来，发现问题回复我，等稳定了再考虑和到主分支去

**Comment by cfk199244** [comment]
好的，我刚看到，今晚试一下，如果这几天没回复，就是没有问题了, 谢谢

**Comment by cfk199244** [comment]
我运行了你的例子，没效果啊.
2个问题
1: 默认页无效了，访问/时报错
2: 
   在#user下输入2222，点击登陆 (登陆显示出来了, 但是返回上一页时,2222还是被清空了)

目前我能看到生效的就是#user下点登陆，再点注册. 同一个chidren里的路由进行切换才有效..

**Comment by wikieswan** [comment]
这两个都修复了 v2 分支
谢谢你的反馈
